name: lendify
description: "ShareItToo is a vibrant peer-to-peer marketplace for renting anything, from power tools to party gear, offering an intuitive, Airbnb-inspired experience with robust localization and a powerful Flutter foundation."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  share_plus: ^12.0.0
  flutter_svg: ^2.0.0
  mobile_scanner: ^7.0.0
  http: ^1.2.0
  qr_flutter: ^4.0.0
  url_launcher: ^6.0.0
  file_picker: '>=8.1.2'
  geolocator: 13.0.4
  image_picker: '>=1.1.2'
  video_player: '>=2.9.2'
  provider: ^6.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
